name: Create env file advanced

on: [push]

jobs:
    create-env-file-mid:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Create .env file
              run: |
                  touch .env
                  echo ${{secrets.TEST_SECRET_KEYS}} >> .env
            - name: Test printing your secret (Remove this step in production)
              run: cat $HOME/secrets/my_secret.json
