name: Deploy Application

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        env:
            ENVIRONMENT: production
            DEPLOYMENT_URL: https://baeldung.com
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Deploy to Server
              run: |
                  curl -X POST ${{ env.DEPLOYMENT_URL }} \
                  -H "Content-Type: application/json" \
                  -d '{"environment":"${{ env.ENVIRONMENT }}"}'
